# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: hounddd.lightgallery::lang.common.gallery

# Model Form Field configuration
form: $/hounddd/lightgallery/models/gallery/fields.yaml

# Model Class name
modelClass: Hounddd\lightGallery\Models\Gallery

# Default redirect location
defaultRedirect: hounddd/lightgallery/galleries

# Create page
create:
    title: hounddd.lightgallery::lang.galleries.new_gallery
    redirect: hounddd/lightgallery/galleries/update/:id
    redirectClose: hounddd/lightgallery/galleries

# Update page
update:
    title: hounddd.lightgallery::lang.galleries.update_gallery
    redirect: hounddd/lightgallery/galleries
    redirectClose: hounddd/lightgallery/galleries

# Preview page
preview:
    title: hounddd.lightgallery::lang.galleries.preview_gallery